CertifaiAI/cdle-traininglabs

README.md
dl4j-cv-labs/src/main/java/global/skymind/solution/facial_recognition/FaceRecognitionWebcam.java
dl4j-cv-labs/src/main/java/global/skymind/solution/facial_recognition/identification/DistanceFaceIdentifier.java
dl4j-cv-labs/src/main/java/global/skymind/solution/facial_recognition/identification/feature/FaceFeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/solution/facial_recognition/identification/feature/IFaceFeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/solution/facial_recognition/identification/feature/RamokFaceNetFeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/solution/facial_recognition/identification/feature/VGG16FeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/solution/object_detection/AvocadoBananaDetector_TinyYOLO.java
dl4j-cv-labs/src/main/java/global/skymind/solution/object_detection/AvocadoBananaDetector_YOLOv2.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/FaceRecognitionWebcam.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/identification/DistanceFaceIdentifier.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/identification/FaceIdentifier.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/identification/feature/FaceFeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/identification/feature/IFaceFeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/identification/feature/RamokFaceNetFeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/training/facial_recognition/identification/feature/VGG16FeatureProvider.java
dl4j-cv-labs/src/main/java/global/skymind/training/object_detection/AvocadoBananaDetector_TinyYOLO.java
dl4j-cv-labs/src/main/java/global/skymind/training/object_detection/AvocadoBananaDetector_YOLOv2.java

A mini PR to
1. further improve example code with more detailed descriptions
2. update README
3. Simplify face recognition code
[  ] Mac  
[  ] Others  (State here -> xxx )

mini PR to simply code

---

dl4j-labs/src/main/java/global/skymind/solution/datavec/LoadImageAndTransform.java
dl4j-labs/src/main/java/global/skymind/training/datavec/LoadImageAndTransform.java

Fix minor mistake in dataVec
[X] Windows  
[  ] Mac  

minor correction

---

README.md

Update readme to include hall of fame

---

dl4j-cv-labs/pom.xml
dl4j-labs/pom.xml
pom.xml

Cw bug fix cuda default backend

---

dl4j-cv-labs/pom.xml
dl4j-cv-labs/src/main/resources/log4j.properties
dl4j-labs/pom.xml
dl4j-labs/src/main/resources/log4j.properties
pom.xml

Adding proper logging to the repository

---

dl4j-labs/src/main/java/global/skymind/solution/VAE/VAECreditAnomaly.java
dl4j-labs/src/main/java/global/skymind/solution/humanactivity/HumanActivityClassificationCNNLSTM.java
dl4j-labs/src/main/java/global/skymind/solution/humanactivity/HumanActivityClassificationLSTM.java
dl4j-labs/src/main/java/global/skymind/training/VAE/VAECreditAnomaly.java
dl4j-labs/src/main/java/global/skymind/training/humanactivity/HumanActivityClassificationCNNLSTM.java
dl4j-labs/src/main/java/global/skymind/training/humanactivity/HumanActivityClassificationLSTM.java

fix import for zip4j version 2.2.6

---

dl4j-labs/src/main/java/global/skymind/solution/convolution/objectdetection/ImageObjectDetection.java
dl4j-labs/src/main/java/global/skymind/solution/convolution/objectdetection/VideoObjectDetection.java
dl4j-labs/src/main/java/global/skymind/solution/convolution/objectdetection/WebCamObjectDetection.java
dl4j-labs/src/main/java/global/skymind/training/convolution/objectdetection/ImageObjectDetection.java
dl4j-labs/src/main/java/global/skymind/training/convolution/objectdetection/VideoObjectDetection.java
dl4j-labs/src/main/java/global/skymind/training/convolution/objectdetection/WebCamObjectDetection.java

Tested On:
[  ] Mac  
Add example for YOLOv2 Inference on a input image.

Add example for YOLOv2 Inference on a input image.

---

dl4j-cv-labs/pom.xml
dl4j-labs/pom.xml
dl4j-labs/src/main/java/global/skymind/solution/dataexamples/ImageDrawer.java
dl4j-labs/src/main/java/global/skymind/solution/datavec/LoadCSV.java
dl4j-labs/src/main/java/global/skymind/solution/datavec/LoadImageAndTransform.java
dl4j-labs/src/main/java/global/skymind/solution/feedforward/SimplestNetwork.java
dl4j-labs/src/main/java/global/skymind/solution/feedforward/detectgender/PredictGenderTrain.java
dl4j-labs/src/main/java/global/skymind/training/datavec/LoadCSV.java
dl4j-labs/src/main/java/global/skymind/training/datavec/LoadImageAndTransform.java
dl4j-labs/src/main/java/global/skymind/training/feedforward/detectgender/PredictGenderTrain.java
pom.xml

Tested by removing the .m2/repository folder and let it re-download again, all the example can run
[  ] Windows  
[  ] Mac  

Remove unused dependency

---

.gitignore

add pattern matching to ignore all *zip

---

README.md

fix broken links, reformatted showcase into folder-based

---

dl4j-cv-labs/src/main/java/ai/certifai/training/facial_recognition/FaceRecognitionWebcam.java
dl4j-cv-labs/src/main/java/ai/certifai/training/image_processing/Quantization.java

[ X] Windows  
[  ] Mac  
@jingzhi93

Fixed old package import

---

README.md

When you added a new program / programs , put a cross on the OS that you have test it on  
[  ] Mac  
@jingzhi93

[WIP] update README.md

---

dl4j-cv-labs/pom.xml
pom.xml

added ffmpeg maven dependencies to solve ffmpegframegrabber issue

---

dl4j-spark-labs/src/main/java/ai/certifai/HelloWorldSpark.java

[ X] Windows  
[  ] Mac  
@kenghooi-teoh

change to certifai.ai

---

dl4j-labs/src/main/java/ai/certifai/solution/classification/Multiclass.java
dl4j-labs/src/main/java/ai/certifai/training/classification/Multiclass.java

resolve #119       
###When you added a new program / programs , put a cross on the  OS that you have test it on  
[  ] Mac  

add license, author, description 

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Added badges for open source TrainingLabs & improve PULL_REQUEST_TEMPLATE

---

dl4j-cv-labs/src/main/resources/config.properties
dl4j-labs/src/main/resources/config.properties

Latest url updated in config.properties for both dl4j-labs and dl4j-cv-labs as the folders in wasabi are restructured as per Github's Training Labs folder. 
Fixes # (issue)
- [ X] Windows  

latest url update for config.properties

---

dl4j-cv-labs/src/main/java/ai/certifai/solution/image_processing/Quantization.java
dl4j-cv-labs/src/main/java/ai/certifai/solution/image_processing/utils/display/JPanelDisplay.java
dl4j-cv-labs/src/main/java/ai/certifai/training/image_processing/Quantization.java
dl4j-cv-labs/src/main/java/ai/certifai/training/image_processing/utils/display/JPanelDisplay.java
dl4j-labs/src/main/java/ai/certifai/solution/regression/PlotUtil.java
dl4j-labs/src/main/java/ai/certifai/training/regression/PlotUtil.java

Updated package path and repositioned it under License.
Fixes # https://github.com/CertifaiAI/TrainingLabs/issues/149

Updated package path and repositioned it under License

---

README.md

remove sourcerer.io link

---

.github/workflows/build.yml
pom.xml

- Added workflow file to be used for automated code test using Sonar Cloud.
- Added JavaFX profile which is used to download JavaFX dependencies & be used in Java 11 environment ( just for testing purpose in GitHub Action )
- Link to Sonar Cloud project is as follows:
https://sonarcloud.io/dashboard?id=CertifaiAI_TrainingLabs

Adding automated code test workflow with Sonar Cloud & adding JavaFX profile 

---

pom.xml

Remove incorrect prompt comment of package name
to prevent student confused and cause compile time error
[Misleading prompt message](https://github.com/CertifaiAI/cdle-traininglabs/blob/main/pom.xml#L34)
[Package Reference](https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-cuda-10.0)
Fixes # (issue)

📝 Update pom.xml

---

pom.xml

- Update pom file with javafx version declaration in property section

Update pom file with javafx version declaration 

---

dl4j-cv-labs/pom.xml
dl4j-labs/pom.xml
pom.xml

- Updated artifactId & URL in pom files 
Fixes #164 

Updated artifactId & URL in pom file

---

README.md

- Update Discord Badge's URL in README file

Update Discord's URL

---

.github/ISSUE_TEMPLATE/config.yml

- Adding an Issue config file to point FAQ to [Certifai's wiki](https://github.com/CertifaiAI/CertifAI-Knowledge-Base/wiki)
- Example of the template as below:

Create config file for Issue template

---

.github/workflows/auto_comment.yml

- Adding an auto comment workflow whenever an issue is raised. Promote friendliness in a repo.
- Example as below:

Create Issues auto comment workflow
